/**:
  ros__parameters:
    dvl_ip_address: 192.168.194.95
    velocity_frame_id: dvl_A50/velocity_link
    position_frame_id: dvl_A50/position_link


    # DVL Nav Interface Params
    odom_frame_id: dvl_odom         # The parent Frame ID used for the Odometry msg
    child_frame_id: base_link       # If the child frame id is the same as position_frame_id TF should not be published
    orientation_variance: 0.15
    publish_tf: True


    # Static TF Publisher Params
    dvl_to_base_translation: [0.0, 0.0, 0.0] # x, y, z in meters
    dvl_to_base_rotation: [1.0, 0.0, 0.0, 0.0] # x, y, z, w quaternion  (Z down to Z up)